
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.EN]: {
    title: 'BaruaAI',
    heroTitle: 'Create a Professional Cover Letter in Minutes',
    heroSub: 'Generate tailored, high-impact cover letters for Government, NGO, and Private sector roles. Fully supports English and Kiswahili with professional formatting.',
    createBtn: 'Create Your Letter',
    subtitle: 'Generator Form',
    personalInfo: 'Personal Information',
    employerInfo: 'Employer Information',
    jobDetails: 'Job Details',
    documents: 'Documents',
    styleSettings: 'Language & Tone',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    applicantAddress: 'Applicant Address',
    employerAddress: 'Employer Address',
    jobTitle: 'Job Title / Position Applied For',
    companyName: 'Organization / Company / Ministry Name',
    department: 'Department',
    institutionType: 'Institution Type',
    generationLanguage: 'Writing Language',
    toneLabel: 'Letter Tone',
    toneFriendly: 'Friendly',
    toneFriendlyDesc: 'Warm and polite',
    toneProfessional: 'Professional',
    toneProfessionalDesc: 'Formal and official',
    toneBold: 'Bold',
    toneBoldDesc: 'Confident and impactful',
    jobDescriptionLabel: 'Paste Job Description',
    uploadCv: 'Upload CV (PDF or DOC)',
    cvHelper: 'Used only to personalize your letter',
    generateBtn: 'Generate Cover Letter',
    generating: 'Generating your letter...',
    previewTitle: 'Letter Preview',
    downloadPdf: 'Print / Save PDF',
    copyText: 'Copy to Clipboard',
    govt: 'Government',
    ngo: 'NGO',
    private: 'Private Sector',
    placeholderName: 'e.g., John Doe',
    placeholderEmail: 'john.doe@example.com',
    placeholderJob: 'e.g., Senior Accountant',
    placeholderCompany: 'e.g., Ministry of Education / GreenTech Solutions',
    placeholderDept: 'e.g., Finance & Administration',
    placeholderAddress: 'P.O. Box 123, City, Country',
    placeholderPhone: '+254...',
    placeholderJobDesc: 'Paste the requirements and responsibilities of the job here...',
    footerTagline: 'Professional career tools for the modern workforce.',
    optional: 'Optional',
    required: 'Required',
    langEn: 'English',
    langSw: 'Kiswahili'
  },
  [Language.SW]: {
    title: 'BaruaAI',
    heroTitle: 'Andaa Barua ya Maombi ya Kazi ya Kitaalamu kwa Dakika Chache',
    heroSub: 'Tengeneza barua bora zilizoboreshwa kwa nafasi za Serikali, NGO, na Sekta Binafsi. Inasaidia kikamilifu Kiingereza na Kiswahili kwa mpangilio wa kitaalamu.',
    createBtn: 'Anza Kutengeneza',
    subtitle: 'Fomu ya Kutengeneza',
    personalInfo: 'Taarifa Binafsi',
    employerInfo: 'Taarifa za Mwajiri',
    jobDetails: 'Taarifa za Kazi',
    documents: 'Nyaraka',
    styleSettings: 'Lugha na Toni',
    fullName: 'Jina Kamili',
    email: 'Barua Pepe',
    phone: 'Namba ya Simu',
    applicantAddress: 'Anwani ya Mwombaji',
    employerAddress: 'Anwani ya Mwajiri',
    jobTitle: 'Cheo cha Kazi Unachoomba',
    companyName: 'Jina la Taasisi / Kampuni / Wizara',
    department: 'Idara',
    institutionType: 'Aina ya Taasisi',
    generationLanguage: 'Lugha ya Kuandika',
    toneLabel: 'Toni ya Barua',
    toneFriendly: 'Kirafiki',
    toneFriendlyDesc: 'Changamfu na adabu',
    toneProfessional: 'Kitaalamu',
    toneProfessionalDesc: 'Rasmi na kiofisi',
    toneBold: 'Kishujaa',
    toneBoldDesc: 'Ujasiri na ushawishi',
    jobDescriptionLabel: 'Bandika Maelezo ya Kazi',
    uploadCv: 'Pakia CV (PDF au DOC)',
    cvHelper: 'Inatumika tu kuboresha barua yako',
    generateBtn: 'Tengeneza Barua',
    generating: 'Inatengeneza barua yako...',
    previewTitle: 'Uhakiki wa Barua',
    downloadPdf: 'Chapisha / Hifadhi PDF',
    copyText: 'Nakili Maandishi',
    govt: 'Serikali',
    ngo: 'NGO (Asasi Isiyo ya Kiserikali)',
    private: 'Sekta Binafsi',
    placeholderName: 'k.m., Juma Hamisi',
    placeholderEmail: 'juma.hamisi@pepe.com',
    placeholderJob: 'k.m., Mhasibu Mkuu',
    placeholderCompany: 'k.m., Wizara ya Elimu / Kampuni ya GreenTech',
    placeholderDept: 'k.m., Fedha na Utawala',
    placeholderAddress: 'S.L.P 123, Mji, Nchi',
    placeholderPhone: '+255...',
    placeholderJobDesc: 'Bandika vigezo na majukumu ya kazi hapa...',
    footerTagline: 'Zana za kitaalamu za kazi kwa nguvu kazi ya kisasa.',
    optional: 'Hiari',
    required: 'Lazima',
    langEn: 'Kiingereza',
    langSw: 'Kiswahili'
  }
};
